plugins {
    id 'java'
}

ext {
    gdxVersion = '1.12.1'
}

allprojects {
    repositories {
        mavenCentral()
        google()
    }

    apply plugin: 'java-library'

    java {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }

    tasks.withType(JavaCompile) {
        options.encoding = 'UTF-8'
    }
}

